# Generated by Django 6.1 on 2026-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributioncategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
