# Generated by Django 6.1 on 2026-08-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_alter_contributioncategory_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribution_types",
                        to="contributions.contributioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution Type",
                "verbose_name_plural": "Contribution Types",
                "ordering": ["category", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"),
                        name="unique_contribution_type_per_category",
                    )
                ],
            },
        ),
    ]
