# Generated by Django 6.1 on 2026-08-20 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0003_contributiontype"),
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(help_text="First day of the contribution month."),
                ),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contribution_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="contributions.contributiontype",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribution_schedules",
                        to="memberships.membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution Schedule",
                "verbose_name_plural": "Contribution Schedules",
                "ordering": ["-period", "membership", "contribution_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("membership", "contribution_type", "period"),
                        name="unique_schedule_per_membership_type_period",
                    )
                ],
            },
        ),
    ]
