# Generated by Django 6.1 on 2026-08-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0006_contributionschedule_waived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionWaiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("waived", "Waived"), ("restored", "Restored")],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribution_waiver_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiver_history",
                        to="contributions.contributionschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution Waiver History",
                "verbose_name_plural": "Contribution Waiver Histories",
                "ordering": ["-performed_at"],
            },
        ),
    ]
