# Generated by Django 6.1 on 2026-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="code",
            field=models.CharField(default="UMJ", max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
